-- =====================================================
-- DREAM SUITE INITIALIZATION
-- =====================================================
-- Creates tables for AI analytics, memory, and chat
-- Enables pgvector for semantic search
-- =====================================================

-- 1. Enable Vector Extension (for AI Memory)
CREATE EXTENSION IF NOT EXISTS vector;

-- 2. Daily Metrics (Raw Data Log)
CREATE TABLE IF NOT EXISTS daily_metrics (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  artist_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  platform TEXT NOT NULL, -- 'spotify', 'instagram', 'tiktok', 'youtube', 'email'
  metric_type TEXT NOT NULL, -- 'followers', 'streams', 'engagement_rate', 'views'
  metric_value NUMERIC NOT NULL,
  collected_at TIMESTAMPTZ DEFAULT NOW(),
  
  -- Metadata for context (e.g., specific post ID for engagement)
  metadata JSONB DEFAULT '{}'::jsonb
);

-- Index for fast time-series querying
CREATE INDEX idx_daily_metrics_artist_platform ON daily_metrics(artist_id, platform, collected_at DESC);

-- 3. AI Insights (Agent Outputs)
CREATE TABLE IF NOT EXISTS ai_insights (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  artist_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  insight_type TEXT NOT NULL, -- 'brand_analysis', 'content_strategy', 'vote_of_confidence'
  content JSONB NOT NULL, -- Structured insight data
  is_read BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_ai_insights_artist ON ai_insights(artist_id, created_at DESC);

-- 4. Artist Memory (Vector Store)
CREATE TABLE IF NOT EXISTS artist_memory (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  artist_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  content TEXT NOT NULL, -- The text chunk to remember
  embedding vector(1536), -- OpenAI embedding dimension
  metadata JSONB DEFAULT '{}'::jsonb, -- Source, tags, date
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index for vector similarity search (IVFFlat or HNSW)
-- Using IVFFlat for now as it's standard for Supabase
CREATE INDEX idx_artist_memory_embedding ON artist_memory 
USING ivfflat (embedding vector_cosine_ops)
WITH (lists = 100);

-- 5. Chat Messages (Conversation History)
CREATE TABLE IF NOT EXISTS chat_messages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  artist_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  role TEXT NOT NULL CHECK (role IN ('user', 'assistant', 'system')),
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_chat_messages_artist ON chat_messages(artist_id, created_at ASC);

-- =====================================================
-- ROW LEVEL SECURITY (RLS)
-- =====================================================

-- Enable RLS
ALTER TABLE daily_metrics ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_insights ENABLE ROW LEVEL SECURITY;
ALTER TABLE artist_memory ENABLE ROW LEVEL SECURITY;
ALTER TABLE chat_messages ENABLE ROW LEVEL SECURITY;

-- Policies (Users can only access their own data)

-- Daily Metrics
CREATE POLICY "Users can read own metrics" ON daily_metrics
  FOR SELECT TO authenticated USING (artist_id = auth.uid());
CREATE POLICY "Users can insert own metrics" ON daily_metrics
  FOR INSERT TO authenticated WITH CHECK (artist_id = auth.uid());

-- AI Insights
CREATE POLICY "Users can read own insights" ON ai_insights
  FOR SELECT TO authenticated USING (artist_id = auth.uid());
-- Note: Usually AI/System inserts insights, but we allow auth user for now (e.g. edge function acting as user)
CREATE POLICY "Users can insert own insights" ON ai_insights
  FOR INSERT TO authenticated WITH CHECK (artist_id = auth.uid());
CREATE POLICY "Users can update own insights (mark read)" ON ai_insights
  FOR UPDATE TO authenticated USING (artist_id = auth.uid());

-- Artist Memory
CREATE POLICY "Users can read own memory" ON artist_memory
  FOR SELECT TO authenticated USING (artist_id = auth.uid());
CREATE POLICY "Users can insert own memory" ON artist_memory
  FOR INSERT TO authenticated WITH CHECK (artist_id = auth.uid());

-- Chat Messages
CREATE POLICY "Users can read own chat" ON chat_messages
  FOR SELECT TO authenticated USING (artist_id = auth.uid());
CREATE POLICY "Users can insert own chat" ON chat_messages
  FOR INSERT TO authenticated WITH CHECK (artist_id = auth.uid());

-- =====================================================
-- COMMENTS
-- =====================================================
COMMENT ON TABLE daily_metrics IS 'Raw time-series data from connected platforms';
COMMENT ON TABLE ai_insights IS 'Strategic advice and analysis generated by AI agents';
COMMENT ON TABLE artist_memory IS 'Long-term semantic memory for the AI using vector embeddings';
COMMENT ON TABLE chat_messages IS 'Conversation history between artist and AI agent';
